version: '3.3'
services:
  thymosight:
    image: sc-registry.fredhutch.org/thymosight:latest
    networks:
      - proxy
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.thymosight.rule=Host(`thymosight.fredhutch.org`)"
        - "traefik.http.routers.thymosight-secured.rule=Host(`thymosight.fredhutch.org`)"
        - "traefik.http.routers.thymosight.entrypoints=web,web-secured"
        - "traefik.http.services.thymosight.loadbalancer.server.port=3838"
        - "traefik.http.routers.thymosight.tls=true"
        - "org.fredhutch.app.owner=akousa@coh.org,kcooper2@fredhutch.org,jdudakov@fredhutch.org"
        - "org.fredhutch.github.repo=thymosight"


networks:
  proxy:
    external: true
